services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - 5432:5432
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: log

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  mongodb:
    image: mongo 
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw 

    ports:
      - 27017:27017

    volumes: 
      - mongodata:/var/lib/mongodb/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    networks:
      - rabbitnet

  auction-svc: 
    image: salman484/auction-svc:latest
    build: 
      context: .
      dockerfile: AuctionService/Dockerfile

    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres;Database=AuctionDB;User Id=postgres;Password=log
      - IdentityServiceUrl=http://identity-svc

    ports:
      - 5003:80
    depends_on:
      - mongodb
      - rabbitmq

    
      


networks:
  rabbitnet:
    driver: bridge      


volumes:
  mongodata:
